/*
 * This file is part of the KubeVirt project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright The KubeVirt Authors.
 *
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1alpha1 "kubevirt.io/virt-import-api/core/v1alpha1"
	corev1alpha1 "kubevirt.io/virt-import-client-go/virtimport/typed/core/v1alpha1"
)

// fakeVirtualMachineImports implements VirtualMachineImportInterface
type fakeVirtualMachineImports struct {
	*gentype.FakeClientWithList[*v1alpha1.VirtualMachineImport, *v1alpha1.VirtualMachineImportList]
	Fake *FakeImportV1alpha1
}

func newFakeVirtualMachineImports(fake *FakeImportV1alpha1, namespace string) corev1alpha1.VirtualMachineImportInterface {
	return &fakeVirtualMachineImports{
		gentype.NewFakeClientWithList[*v1alpha1.VirtualMachineImport, *v1alpha1.VirtualMachineImportList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("virtualmachineimports"),
			v1alpha1.SchemeGroupVersion.WithKind("VirtualMachineImport"),
			func() *v1alpha1.VirtualMachineImport { return &v1alpha1.VirtualMachineImport{} },
			func() *v1alpha1.VirtualMachineImportList { return &v1alpha1.VirtualMachineImportList{} },
			func(dst, src *v1alpha1.VirtualMachineImportList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.VirtualMachineImportList) []*v1alpha1.VirtualMachineImport {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.VirtualMachineImportList, items []*v1alpha1.VirtualMachineImport) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
