/*
 * This file is part of the KubeVirt project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright The KubeVirt Authors.
 *
 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	corev1alpha1 "kubevirt.io/virt-import-api/core/v1alpha1"
	scheme "kubevirt.io/virt-import-client-go/virtimport/scheme"
)

// VirtualMachineImportsGetter has a method to return a VirtualMachineImportInterface.
// A group's client should implement this interface.
type VirtualMachineImportsGetter interface {
	VirtualMachineImports(namespace string) VirtualMachineImportInterface
}

// VirtualMachineImportInterface has methods to work with VirtualMachineImport resources.
type VirtualMachineImportInterface interface {
	Create(ctx context.Context, virtualMachineImport *corev1alpha1.VirtualMachineImport, opts v1.CreateOptions) (*corev1alpha1.VirtualMachineImport, error)
	Update(ctx context.Context, virtualMachineImport *corev1alpha1.VirtualMachineImport, opts v1.UpdateOptions) (*corev1alpha1.VirtualMachineImport, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, virtualMachineImport *corev1alpha1.VirtualMachineImport, opts v1.UpdateOptions) (*corev1alpha1.VirtualMachineImport, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.VirtualMachineImport, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.VirtualMachineImportList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.VirtualMachineImport, err error)
	VirtualMachineImportExpansion
}

// virtualMachineImports implements VirtualMachineImportInterface
type virtualMachineImports struct {
	*gentype.ClientWithList[*corev1alpha1.VirtualMachineImport, *corev1alpha1.VirtualMachineImportList]
}

// newVirtualMachineImports returns a VirtualMachineImports
func newVirtualMachineImports(c *ImportV1alpha1Client, namespace string) *virtualMachineImports {
	return &virtualMachineImports{
		gentype.NewClientWithList[*corev1alpha1.VirtualMachineImport, *corev1alpha1.VirtualMachineImportList](
			"virtualmachineimports",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1alpha1.VirtualMachineImport { return &corev1alpha1.VirtualMachineImport{} },
			func() *corev1alpha1.VirtualMachineImportList { return &corev1alpha1.VirtualMachineImportList{} },
		),
	}
}
